export type Booking = {
  packageName: string;
  customerName: string;
  contact: string;
  email: string;
  status: boolean;
  adultCount: string;
  childCount: string;
  numberOfRooms: string;
  hotel: string;
  tourDate: string;
  note: string;
};
export type BookingsType = {
  _id: string;
  packageName: string;
  customerName: string;
  contact: string;
  email: string;
  status: boolean;
  adultCount: string;
  childCount: string;
  numberOfRooms: string;
  hotel: string;
  tourDate: string;
  note: string;
  createdAt: any;
  updatedAt: any;
  __v: number;
};
